# noinspection SpellCheckingInspection
api : "gAAAAABpVCZ_06_IgKhbQwKkUEWwLhV6rTq0hKhkzRWKNNQq-AddsuOHz80vt--tXV9o6WOXIQkKfJ4xl75gUw3wdDWhPmE7XLmLYfvu1A3Eo9EfRSpy2FJqV1yG-5phmkJNswdlTZCFlPIKRzzgtZD4NuylOQRjBw=="
key : "D8MOy-rPgDiVT24AFB5pjupFbZjh59xBGh0lWBNt1A0="